// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase credentials
if (!SUPABASE_URL || SUPABASE_URL === 'your_supabase_project_url') {
  console.error('❌ VITE_SUPABASE_URL is not configured in .env file');
  console.error('Please edit .env and add your Supabase project URL');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'your_supabase_publishable_key') {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is not configured in .env file');
  console.error('Please edit .env and add your Supabase publishable key');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);